### PR TITLE
lower_bound and upper_bound operations for set

### PR DESCRIPTION
**Pull request by wwwVladislav**
This PR contains lower_bound and upper_bound operations for set.

### CODE REVIEW

**Comment by glouw** [comment]
Greatly appreciate this. Will merge once CI is complete.

**Comment by glouw** [comment]
Much thanks, I'll add your handle to the acknowledgements

**Comment by wwwVladislav** [comment]
You are welcome. Thanks for this great library too. (:

**Comment by glouw** [comment]
You're welcome!

**Pull request merged**
